### ISSUE TITLE
Location to copy dictionarys

### ISSUE THREAD

**Issue by BA-Baracus-BBB** [chausner/TranslateWithDictCC#2]
Hi,
is there another way to add dictionaries other than through the user interface?
Can I copy the files to a folder? Or integrate in another way?

**Comment by chausner** [comment]
At the moment, there is no officially supported way to import dictionaries other than through the user interface. Under the hood, the app uses an SQLite database to store and index dictionaries. When you import a dictionary in the app, it populates the database. The file is stored at %LOCALAPPDATA%\Packages\3941373C7C64E.Translatewithdict.cc_76yyh5d59m62c\LocalState\dictionaries.db.

Can you please elaborate why you want to import dictionaries outside of the app?

**Comment by BA-Baracus-BBB** [comment]
Thanx.
now it works perfectly with my software deployment tool in a multi-user environment.

**Comment by chausner** [comment]
Glad you found a workaround!
